### ISSUE TITLE
Memory requirement

### ISSUE THREAD

**Issue by xizaoqu** [stroopwafl/self-guidance#4]
Hi, thanks for your work. I run it on a 3090 GPU. But it shows CUDA out of memory. What is the memory requirement of the script?

**Comment by lishaoxu1994** [comment]
> Hi, thanks for your work. I run it on a 3090 GPU. But it shows CUDA out of memory. What is the memory requirement of the script?

I'm having the same problem, can you please tell me how you solved it?

**Comment by ziyang1106** [comment]
> > Hi, thanks for your work. I run it on a 3090 GPU. But it shows CUDA out of memory. What is the memory requirement of the script?
> 
> I'm having the same problem, can you please tell me how you solved it?

It takes approximately 30G to run this code on one A800 GPU.
